dist: xenial
sudo: required
language: node_js
node_js:
  - "8"
matrix:
  include:
    - os: linux
      dist: xenial
      before_install:
      - sudo add-apt-repository ppa:ethereum/ethereum -y
      - sudo apt-get update
      - sudo apt-get install build-essential -y
      - sudo apt-get install gcc g++ libssl-dev libudev-dev pkg-config
      - curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - rm -rf node_modules
      - mkdir migrations
install:
  - npm install truffle
  - npm install ganache-cli
  - npm install
allow_failures:
  - env: SOLIDITY_COVERAGE=true
jobs:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
    - env: SOLC_NIGHTLY=true
  include:
    - stage: tests
      name: "unit tests"
      script: npm run test
    - stage: tests
      name: "unit tests with coverage"
      script: npm run test
      env: SOLIDITY_COVERAGE=true
